# Bank of Anthos workload manifests + network boundary policies.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base-workloads
components:
  - ../components/network-boundaries
