apiVersion: apps/v1
kind: Deployment
metadata:
  name: balancereader
spec:
  template:
    spec:
      serviceAccountName: bank-of-anthos
      containers:
        - name: balancereader
          env:
            - name: LEDGER_DB_SECRET_ID
              $patch: delete
            - name: GCP_PROJECT
              $patch: delete
            - name: ENABLE_TRACING
              value: "false"
            - name: ENABLE_METRICS
              value: "false"
            - name: JVM_OPTS
              value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms128m -Xmx256m
          envFrom:
            - configMapRef:
                name: ledger-db-config
